{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ef8853bc",
   "metadata": {},
   "outputs": [],
   "source": [
    "---------------------------------------------------------------------------\n",
    "TypeError                                 Traceback (most recent call last)\n",
    "Input In [7], in <cell line: 2>()\n",
    "      1 import numpy as np\n",
    "----> 2 trainFeatures = np.array[[1, 11, 8], [1, 8, 11]]\n",
    "      3 trainTargets = np.array[[0], [1]]\n",
    "\n",
    "TypeError: 'builtin_function_or_method' object is not subscriptable\n",
    "    \n",
    "# The problem of mistaken use of [] (should use () )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7b07200e",
   "metadata": {},
   "outputs": [],
   "source": [
    "---------------------------------------------------------------------------\n",
    "TypeError                                 Traceback (most recent call last)\n",
    "Input In [8], in <cell line: 2>()\n",
    "      1 import numpy as np\n",
    "----> 2 trainFeatures = np.array([1, 11, 8], [1, 8, 11])\n",
    "      3 trainTargets = np.array([0], [1])\n",
    "\n",
    "TypeError: Field elements must be 2- or 3-tuples, got '1'\n",
    "    \n",
    "# Beacuse we shall use a. [] to include all data, like [[0], [1]]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3ca7aec5",
   "metadata": {},
   "outputs": [],
   "source": [
    "TypeError                                 Traceback (most recent call last)\n",
    "Input In [45], in <cell line: 1>()\n",
    "----> 1 linearRegressor = LinearRegression(3)\n",
    "\n",
    "Input In [44], in LinearRegression.__init__(self, inputDimension, learningRate)\n",
    "      8 def __init__(self, inputDimension: int, learningRate: float = 0.01):\n",
    "      9     super().__init__()\n",
    "---> 10     self.weights = nn.parameter(torch.randn(inputDimension, requires_grad=True))\n",
    "     11     self.bias = nn.parameter(torch.randn(1, requires_grad=True))\n",
    "     12     self.learningRate = lr\n",
    "\n",
    "TypeError: 'module' object is not callable\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cd888469",
   "metadata": {},
   "outputs": [],
   "source": [
    "---------------------------------------------------------------------------\n",
    "RuntimeError                              Traceback (most recent call last)\n",
    "Input In [74], in <cell line: 1>()\n",
    "----> 1 linearRegressor(torchTrainFeatures)\n",
    "\n",
    "File ~/anaconda3/envs/kokoa/lib/python3.10/site-packages/torch/nn/modules/module.py:1501, in Module._call_impl(self, *args, **kwargs)\n",
    "   1496 # If we don't have any hooks, we want to skip the rest of the logic in\n",
    "   1497 # this function, and just call forward.\n",
    "   1498 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks\n",
    "   1499         or _global_backward_pre_hooks or _global_backward_hooks\n",
    "   1500         or _global_forward_hooks or _global_forward_pre_hooks):\n",
    "-> 1501     return forward_call(*args, **kwargs)\n",
    "   1502 # Do not call functions when jit is used\n",
    "   1503 full_backward_hooks, non_full_backward_hooks = [], []\n",
    "\n",
    "Input In [62], in LinearRegression.forward(self, x)\n",
    "     14 def forward(self, x) -> torch.tensor:\n",
    "---> 15     return x @ self.weights + self.bias\n",
    "\n",
    "RuntimeError: expected scalar type Long but found Float\n",
    "    \n",
    "# This error occurs beacuse we need same dtype in torch matrix multiplication\n",
    "\n",
    "\n",
    "# class CustomDataset(Dataset):\n",
    "#     def __init__(self, data, targets) -> NoReturn:\n",
    "#         self.data = torch.from_numpy(data).float()\n",
    "#         self.targets = torch.from_numpy(targets).float()\n",
    "#         add change the dtype in data loader\n",
    "\n",
    "# p.s notice that there are differnt between torch.from_numpy() and torch.tensor(), about the shared memory\n",
    "# https://stackoverflow.com/questions/48482787/pytorch-memory-model-torch-from-numpy-vs-torch-tensor"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a5be29a5",
   "metadata": {},
   "outputs": [],
   "source": [
    "AttributeError                            Traceback (most recent call last)\n",
    "Input In [36], in <cell line: 1>()\n",
    "----> 1 model = LassoLogisticRegression(46)\n",
    "\n",
    "Input In [35], in LassoLogisticRegression.__init__(self, inputDimension)\n",
    "      2 def __init__(self, inputDimension):\n",
    "----> 3     self.weights = nn.Parameter(torch.randn(inputDimension))\n",
    "      4     self.bias = nn.Parameter(torch.randn(1))\n",
    "\n",
    "File ~/anaconda3/envs/kokoa/lib/python3.10/site-packages/torch/nn/modules/module.py:1629, in Module.__setattr__(self, name, value)\n",
    "   1627 if isinstance(value, Parameter):\n",
    "   1628     if params is None:\n",
    "-> 1629         raise AttributeError(\n",
    "   1630             \"cannot assign parameters before Module.__init__() call\")\n",
    "   1631     remove_from(self.__dict__, self._buffers, self._modules, self._non_persistent_buffers_set)\n",
    "   1632     self.register_parameter(name, value)\n",
    "\n",
    "AttributeError: cannot assign parameters before Module.__init__() call\n",
    "    \n",
    "#     This error happen because did'nt implement super().__init__()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "231a5e57",
   "metadata": {},
   "outputs": [],
   "source": [
    "InvalidIndexError                         Traceback (most recent call last)\n",
    "Input In [38], in <cell line: 1>()\n",
    "----> 1 numpyFeatures = data[:, :-1].to_numpy()\n",
    "      2 numpyTargets = data[:, -1].to_numpy()\n",
    "\n",
    "File ~/anaconda3/envs/kokoa/lib/python3.10/site-packages/pandas/core/frame.py:3807, in DataFrame.__getitem__(self, key)\n",
    "   3805 if self.columns.nlevels > 1:\n",
    "   3806     return self._getitem_multilevel(key)\n",
    "-> 3807 indexer = self.columns.get_loc(key)\n",
    "   3808 if is_integer(indexer):\n",
    "   3809     indexer = [indexer]\n",
    "\n",
    "File ~/anaconda3/envs/kokoa/lib/python3.10/site-packages/pandas/core/indexes/base.py:3809, in Index.get_loc(self, key, method, tolerance)\n",
    "   3804         raise KeyError(key) from err\n",
    "   3805     except TypeError:\n",
    "   3806         # If we have a listlike key, _check_indexing_error will raise\n",
    "   3807         #  InvalidIndexError. Otherwise we fall through and re-raise\n",
    "   3808         #  the TypeError.\n",
    "-> 3809         self._check_indexing_error(key)\n",
    "   3810         raise\n",
    "   3812 # GH#42269\n",
    "\n",
    "File ~/anaconda3/envs/kokoa/lib/python3.10/site-packages/pandas/core/indexes/base.py:5925, in Index._check_indexing_error(self, key)\n",
    "   5921 def _check_indexing_error(self, key):\n",
    "   5922     if not is_scalar(key):\n",
    "   5923         # if key is not a scalar, directly raise an error (the code below\n",
    "   5924         # would convert to numpy arrays and raise later any way) - GH29926\n",
    "-> 5925         raise InvalidIndexError(key)\n",
    "\n",
    "InvalidIndexError: (slice(None, None, None), slice(None, -1, None))\n",
    "\n",
    "    \n",
    "# The [] can not be used in this to_numpy(), we shall use .iloc. iloc or loc provides more flexibility and functionality"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
